apiVersion: apps/v1
kind: Deployment
metadata:
  name: ezyevent-api-deployment
  labels:
    app: ezyevent-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ezyevent-api
  template:
    metadata:
      labels:
        app: ezyevent-api
    spec:
      containers:
        - name: ezyevent-api
          image: johnyoat/ezyevent-api:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ezyevent-api-service
  labels:
    app: ezyevent-api
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ezyevent-api
  sessionAffinity: None

